apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sce-batch-data-pvc
spec:
  volumeName: sce-batch-data-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
      
