apiVersion: v1
kind: Secret
metadata:
  name: sce-batch-secret
data:
  DB_USER: c2Nl
  DB_PASSWORD: c2NlX2FiMDEk
  RABBITMQ_USER: cm9vdA==
  RABBITMQ_PASSWORD: aG9sYTEyMw==
  FIRMA_CREDENCIAL: WEV6SVByZXRBWEVzMGVjUmVUaGVzXCFrb2NoZVgyUg==
  TSA_USER: U0lHUEU=
  TSA_PASSWORD: WnhDQ0ZEUkVTNTY0NzJESTY5