apiVersion: v1
kind: Service
metadata:
  name: sce-batch-service
  labels:
    app: sisgoe-job
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: httpexternal
  selector:
    app: sisgoe-job
