apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sce-nacion-data-pvc
spec:
  volumeName: sce-nacion-data-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sce-nacion-installer-pvc
spec:
  volumeName: sce-nacion-installer-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi