apiVersion: v1
kind: Service
metadata:
  name: sce-nacion-backend-service
  labels:
    app: sce-nacion-backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: httpexternal
  selector:
    app: sce-nacion-backend
