apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sce-modelo-api-hpa
  labels:
    app: sce-modelo-api
    tier: backend
    tierType: business
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sce-modelo-api
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70