sonar.projectKey=sce_models_api
sonar.projectName=sce_models_api
sonar.projectVersion=1.0
sonar.language=py
sonar.exclusions=*/_pycache_/, */.spec, */.md, */venv/**
sonar.sources=util,db,models,modules,app.py,bot.py,config.py,secciones_miembros_mesa.py,secciones_rectangulos.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.host.url=http://10.220.80.60:9000/
sonar.login=squ_9e5d188ab327e39c86b24b98748ced91c74b8d5b