sonar.projectKey=sce_nacion_backend
sonar.projectName=sce_nacion_backend
sonar.projectVersion=1.0

sonar.sources=src/main

sonar.java.binaries=target/classes

sonar.sourceEncoding=UTF-8

# Opcional: configuración del servidor SonarQube
sonar.host.url=http://10.220.80.60:9000/
sonar.token=squ_17ba3e623fb9c604b0680c08214f5d4bc7c852311