FROM node:20.9.0 AS  build-stage

WORKDIR /app
COPY package*.json /app/
RUN npm install --legacy-peer-deps
COPY ./ /app/
ARG configuration=production
RUN npm run build -- --output-path=./dist/sce-front/ --configuration "$configuration"



FROM nginx:1.15

ENV TZ=America/Lima

COPY --from=build-stage /app/dist/sce-front/browser /usr/share/nginx/html

COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf
