package pe.gob.onpe.sceorcbackend.model.dto.reporte;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class ComparacionDigitacionAutomaticaDto {
    private String codigoAmbitoElectoral;
    private String nombreAmbitoElectoral;
    private String codigoCentroComputo;
    private String nombreCentroComputo;
    private String codigoUbigeo;
    private String departamento;
    private String provincia;
    private String distrito;
    private String mesa;
    private String numeroCopia;
    private String digitoChequeoEscrutinio;
    private Integer posicion;
    private String descripcion;
    private Integer votoCiudadanos;
    private Integer votoAutomTotal;
    private Integer votoManualTotal;
    private Integer votoAutom1;
    private Integer votoManual1;
    private Integer votoAutom2;
    private Integer votoManual2;
    private Integer votoAutom3;
    private Integer votoManual3;
    private Integer votoAutom4;
    private Integer votoManual4;
    private Integer votoAutom5;
    private Integer votoManual5;
    private Integer votoAutom6;
    private Integer votoManual6;
    private Integer votoAutom7;
    private Integer votoManual7;
    private Integer votoAutom8;
    private Integer votoManual8;
    private Integer votoAutom9;
    private Integer votoManual9;
    private Integer votoAutom10;
    private Integer votoManual10;
    private Integer votoAutom11;
    private Integer votoManual11;
    private Integer votoAutom12;
    private Integer votoManual12;
    private Integer votoAutom13;
    private Integer votoManual13;
    private Integer votoAutom14;
    private Integer votoManual14;
    private Integer votoAutom15;
    private Integer votoManual15;
    private Integer votoAutom16;
    private Integer votoManual16;
    private Integer votoAutom17;
    private Integer votoManual17;
    private Integer votoAutom18;
    private Integer votoManual18;
    private Integer votoAutom19;
    private Integer votoManual19;
    private Integer votoAutom20;
    private Integer votoManual20;
    private Integer votoAutom21;
    private Integer votoManual21;
    private Integer votoAutom22;
    private Integer votoManual22;
    private Integer votoAutom23;
    private Integer votoManual23;
    private Integer votoAutom24;
    private Integer votoManual24;
    private Integer votoAutom25;
    private Integer votoManual25;
    private Integer votoAutom26;
    private Integer votoManual26;
    private Integer votoAutom27;
    private Integer votoManual27;
    private Integer votoAutom28;
    private Integer votoManual28;
    private Integer votoAutom29;
    private Integer votoManual29;
    private Integer votoAutom30;
    private Integer votoManual30;
    private Integer votoAutom31;
    private Integer votoManual31;
    private Integer votoAutom32;
    private Integer votoManual32;
    private String dif1;
    private String dif2;
    private String dif3;
    private String dif4;
    private String dif5;
    private String dif6;
    private String dif7;
    private String dif8;
    private String dif9;
    private String dif10;
    private String dif11;
    private String dif12;
    private String dif13;
    private String dif14;
    private String dif15;
    private String dif16;
    private String dif17;
    private String dif18;
    private String dif19;
    private String dif20;
    private String dif21;
    private String dif22;
    private String dif23;
    private String dif24;
    private String dif25;
    private String dif26;
    private String dif27;
    private String dif28;
    private String dif29;
    private String dif30;
    private String dif31;
    private String dif32;
    private String validacionVoto;

    public void calcularDiferencias() {
        this.dif1 = comparar(votoAutom1, votoManual1);
        this.dif2 = comparar(votoAutom2, votoManual2);
        this.dif3 = comparar(votoAutom3, votoManual3);
        this.dif4 = comparar(votoAutom4, votoManual4);
        this.dif5 = comparar(votoAutom5, votoManual5);
        this.dif6 = comparar(votoAutom6, votoManual6);
        this.dif7 = comparar(votoAutom7, votoManual7);
        this.dif8 = comparar(votoAutom8, votoManual8);
        this.dif9 = comparar(votoAutom9, votoManual9);
        this.dif10 = comparar(votoAutom10, votoManual10);
        this.dif11 = comparar(votoAutom11, votoManual11);
        this.dif12 = comparar(votoAutom12, votoManual12);
        this.dif13 = comparar(votoAutom13, votoManual13);
        this.dif14 = comparar(votoAutom14, votoManual14);
        this.dif15 = comparar(votoAutom15, votoManual15);
        this.dif16 = comparar(votoAutom16, votoManual16);
        this.dif17 = comparar(votoAutom17, votoManual17);
        this.dif18 = comparar(votoAutom18, votoManual18);
        this.dif19 = comparar(votoAutom19, votoManual19);
        this.dif20 = comparar(votoAutom20, votoManual20);
        this.dif21 = comparar(votoAutom21, votoManual21);
        this.dif22 = comparar(votoAutom22, votoManual22);
        this.dif23 = comparar(votoAutom23, votoManual23);
        this.dif24 = comparar(votoAutom24, votoManual24);
        this.dif25 = comparar(votoAutom25, votoManual25);
        this.dif26 = comparar(votoAutom26, votoManual26);
        this.dif27 = comparar(votoAutom27, votoManual27);
        this.dif28 = comparar(votoAutom28, votoManual28);
        this.dif29 = comparar(votoAutom29, votoManual29);
        this.dif30 = comparar(votoAutom30, votoManual30);
        this.dif31 = comparar(votoAutom31, votoManual31);
        this.dif32 = comparar(votoAutom32, votoManual32);
    }

    private String comparar(Integer a, Integer m) {
        if (a == null || m == null) return "NO";
        return !a.equals(m) ? "SI" : "NO";
    }
}
