sonar.projectKey=sce_scaner
sonar.projectName=sce_scaner
sonar.projectVersion=1.0

sonar.sources=src/main

sonar.java.binaries=target/classes

sonar.sourceEncoding=UTF-8

# Opcional: configuración del servidor SonarQube
sonar.host.url=http://10.220.80.60:9000/
sonar.token=squ_8114d9e3646ad905a242fbdb0de5a1734a187adb